'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),express=require('express');
const {PGlite}=require('@electric-sql/pglite');
const {installVenueOwner}=require('./venue-owner');
test('master access routes issue, list and revoke scoped keys without exposing hashes',async()=>{
 const pg=new PGlite();await pg.exec(`CREATE TABLE shaurma_venues(establishment_id text PRIMARY KEY,name text);INSERT INTO shaurma_venues VALUES('SC-MSK-0000000001','Тест');
 CREATE TABLE shaurma_venue_admins(establishment_id text,telegram_user_id text,telegram_username text,telegram_first_name text,role text,permissions jsonb,is_active boolean,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
 INSERT INTO shaurma_venue_admins VALUES('SC-MSK-0000000001','42','owner','Владелец','owner','[]',true,now(),now());
 CREATE TABLE shaurma_venue_invites(id bigserial PRIMARY KEY,establishment_id text REFERENCES shaurma_venues,code_hash text UNIQUE,role text,permissions jsonb,expires_at timestamptz,max_uses int,uses int DEFAULT 0,is_active boolean DEFAULT true,created_by text,created_at timestamptz DEFAULT now(),last_used_at timestamptz,kitchen_enabled boolean DEFAULT true);`);
 const app=express();app.use(express.json());installVenueOwner(app,{DB:pg,ownerOk:req=>req.get('x-owner-token')==='fixture-master',verifyTelegramInitDataWithToken:()=>{throw Error('unsigned')},normalizeMarkerStyle:x=>x,publishVenue(){},pushOwner(){}});
 const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port+'/api/shaurma/admin/establishments/',est='SC-MSK-0000000001',headers={'X-Owner-Token':'fixture-master','Content-Type':'application/json'};
 try{assert.equal((await fetch(base+est+'/admins')).status,401);assert.equal((await fetch(base+est+'/invites')).status,401);let r=await fetch(base+est+'/admins',{headers});assert.equal(r.status,200);assert.equal((await r.json())[0].telegram_user_id,'42');r=await fetch(base+est+'/invites',{headers,method:'POST',body:JSON.stringify({role:'owner'})});assert.equal(r.status,201);const key=await r.json();assert.match(key.claim_code,/^OWN-[A-F0-9]{10}$/);r=await fetch(base+est+'/invites',{headers});const list=await r.json();assert.equal(list.length,1);assert.equal(list[0].kitchen_enabled,true);assert.equal(list[0].code_hash,undefined);assert.equal(list[0].claim_code,undefined);assert.equal((await fetch(base+'SC-MSK-0000000002/invites/'+key.id,{headers,method:'DELETE'})).status,404);assert.equal((await fetch(base+est+'/invites/'+key.id,{headers,method:'DELETE'})).status,200);assert.equal((await (await fetch(base+est+'/invites',{headers})).json())[0].is_active,false)}finally{server.closeAllConnections();await new Promise(r=>server.close(r));await pg.close()}
});
