(() => {
 const {api,money,esc}=SHAURMEG,tg=SHAURMEG.telegram,$=s=>document.querySelector(s);
 let session=sessionStorage.getItem('shaurmeg_venue_owner_session')||'',accesses=[],est='',data=null,menu=[],stream=null;
 function toast(v){$('#toast').textContent=v;$('#toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('#toast').classList.remove('show'),1600)}
 async function call(path,opt={}){opt.headers={...(opt.headers||{}),Authorization:'Bearer '+session};if(opt.body){opt.headers['Content-Type']='application/json';if(typeof opt.body!=='string')opt.body=JSON.stringify(opt.body)}const r=await fetch(api+path,opt);if(!r.ok){const j=await r.json().catch(()=>({}));throw new Error(j.error||'HTTP '+r.status)}return r.json()}
 async function auth(){
   if(session){try{const me=await call('/venue-owner/me');accesses=me.establishments||[];$('#ownerName').textContent=me.user?.first_name||me.user?.username||'OWNER';return true}catch{session='';sessionStorage.removeItem('shaurmeg_venue_owner_session')}}
   if(!tg?.initData)return false;try{const r=await fetch(api+'/venue-owner/auth/telegram',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({initData:tg.initData})});if(!r.ok)throw 0;const j=await r.json();session=j.session;accesses=j.establishments||[];sessionStorage.setItem('shaurmeg_venue_owner_session',session);$('#ownerName').textContent=j.user?.first_name||j.user?.username||'OWNER';return true}catch{return false}
 }
 async function bootstrap(){
   if(!(await auth())){$('#gateText').textContent='Нет действующей Telegram-сессии. Откройте Mini App из бота владельца.';return}
   if(!accesses.length){$('#gateText').textContent='К этому Telegram-аккаунту пока не привязано ни одного заведения. Введите код, который выдал администратор карты.';return}
   $('#gate').classList.add('hidden');$('#venueSelect').innerHTML=accesses.map(x=>'<option value="'+esc(x.establishment_id)+'">'+esc(x.name)+'</option>').join('');est=new URL(location.href).searchParams.get('establishment')||accesses[0].establishment_id;if(!accesses.some(x=>x.establishment_id===est))est=accesses[0].establishment_id;$('#venueSelect').value=est;await load();
 }
 async function claimAccess(){if(!session)return toast('Откройте Mini App через Telegram-бота владельца');const code=$('#claimCode').value.trim();if(!code)return toast('Введите код');try{const j=await call('/venue-owner/claim',{method:'POST',body:{code}});accesses=j.establishments||[];if(!accesses.length)throw new Error('Доступ не появился');$('#gate').classList.add('hidden');$('#venueSelect').innerHTML=accesses.map(x=>'<option value="'+esc(x.establishment_id)+'">'+esc(x.name)+'</option>').join('');est=accesses[0].establishment_id;$('#venueSelect').value=est;await load();toast('Заведение подключено ✓')}catch(e){toast(e.message)}}
 async function load(){data=await call('/venue-owner/establishments/'+encodeURIComponent(est));menu=(data.menu||[]).map(x=>({...x}));$('#vName').value=data.name||'';$('#vAddress').value=data.address||'';$('#vDescription').value=data.description||'';$('#vHours').value=data.hours||'';$('#vPrice').value=data.price_label||'';$('#vMarkerIcon').value=data.marker_style?.icon||'🥙';$('#vMarkerBg').value=data.marker_style?.background||'#10221b';$('#vBuilderEnabled').checked=data.config?.builder_enabled===true;renderMenu();await loadOrders();connect()}
 function renderMenu(){$('#menuEditor').innerHTML=menu.length?menu.map((x,i)=>'<div class="menuEditRow" data-i="'+i+'"><input data-k="n" value="'+esc(x.n||x.name||'')+'" placeholder="Название"><input class="desc" data-k="d" value="'+esc(x.d||x.description||'')+'" placeholder="Описание"><input data-k="p" inputmode="decimal" value="'+esc(x.p??x.price??0)+'" placeholder="₽"><button class="dangerBtn" data-del="'+i+'" type="button">×</button></div>').join(''):'<div class="empty">Добавьте первую позицию</div>'}
 function readMenu(){document.querySelectorAll('.menuEditRow').forEach(row=>{const i=+row.dataset.i,x=menu[i];row.querySelectorAll('[data-k]').forEach(inp=>x[inp.dataset.k]=inp.dataset.k==='p'?+inp.value:inp.value);x.id=x.id||'item_'+Date.now()+'_'+i;x.c=x.c||'shawarma';x.active=true})}
 async function saveProfile(){try{await call('/venue-owner/establishments/'+encodeURIComponent(est)+'/profile',{method:'PATCH',body:{name:$('#vName').value,address:$('#vAddress').value,description:$('#vDescription').value,hours:$('#vHours').value,price_label:$('#vPrice').value,config:{builder_enabled:$('#vBuilderEnabled').checked}}});toast('Профиль сохранён ✓');await load()}catch(e){toast(e.message)}}
 async function saveAppearance(){try{await call('/venue-owner/establishments/'+encodeURIComponent(est)+'/appearance',{method:'PATCH',body:{marker_style:{...(data.marker_style||{}),icon:$('#vMarkerIcon').value||'🥙',background:$('#vMarkerBg').value||'#10221b'}}});toast('Метка обновлена ✓');await load()}catch(e){toast(e.message)}}
 async function saveMenu(){readMenu();try{await call('/venue-owner/establishments/'+encodeURIComponent(est)+'/menu',{method:'PUT',body:{menu,sections:data.sections||[]}});toast('Меню обновлено ✓');await load()}catch(e){toast(e.message)}}
 async function loadOrders(){try{const rows=await call('/venue-owner/establishments/'+encodeURIComponent(est)+'/orders');renderOrders(rows)}catch(e){$('#ordersList').innerHTML='<div class="empty">Не удалось загрузить заказы</div>'}}
 function renderOrders(rows){$('#ordersList').innerHTML=rows.length?rows.map(o=>'<article class="orderCard"><header><b>'+esc(o.order_number)+'</b><span class="status">'+esc(o.status)+'</span></header><small>'+new Date(o.created_at).toLocaleString('ru-RU')+' · '+esc(o.fulfillment_type==='cafe'?'в заведении':'доставка')+'</small><div style="margin-top:7px">'+esc((o.items||[]).map(x=>(x.n||x.name)+' × '+(x.q||1)).join(' · '))+'</div><div style="margin-top:8px;font-size:18px;font-weight:900">'+money(o.total)+'</div><div class="rowBtns" style="margin-top:9px">'+(o.status==='new'?'<button class="plainBtn" data-order="'+o.id+'" data-status="cooking">Принять</button>':'')+(o.status==='cooking'?'<button class="plainBtn" data-order="'+o.id+'" data-status="ready">Готов</button>':'')+(o.status==='ready'?'<button class="primaryBtn" data-order="'+o.id+'" data-status="done">Выдан</button>':'')+(!['done','cancelled'].includes(o.status)?'<button class="dangerBtn" data-order="'+o.id+'" data-status="cancelled">Отменить</button>':'')+'</div></article>').join(''):'<div class="empty">Заказов пока нет</div>'}
 function connect(){stream?.close();stream=new EventSource(api+'/venue-owner/establishments/'+encodeURIComponent(est)+'/stream?owner_session='+encodeURIComponent(session));stream.addEventListener('order',()=>loadOrders());stream.addEventListener('update',()=>loadOrders());stream.onerror=()=>$('#ordersLive').textContent='RECONNECT'}
 document.querySelector('.tabs').onclick=e=>{const b=e.target.closest('[data-tab]');if(!b)return;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));['profile','menu','orders'].forEach(id=>$('#'+id).classList.toggle('hidden',id!==b.dataset.tab))};
 $('#claimBtn').onclick=claimAccess;$('#ordersList').onclick=async e=>{const b=e.target.closest('[data-order]');if(!b)return;b.disabled=true;try{await call('/venue-owner/establishments/'+encodeURIComponent(est)+'/orders/'+b.dataset.order,{method:'PATCH',body:{status:b.dataset.status}});await loadOrders();toast('Статус обновлён')}catch(err){toast(err.message)}finally{b.disabled=false}};$('#venueSelect').onchange=async()=>{est=$('#venueSelect').value;await load()};$('#saveProfile').onclick=saveProfile;$('#saveAppearance').onclick=saveAppearance;$('#saveMenu').onclick=saveMenu;$('#addItem').onclick=()=>{readMenu();menu.push({id:'item_'+Date.now(),n:'Новая позиция',d:'',p:0,c:'shawarma',active:true});renderMenu()};
 $('#menuEditor').onclick=e=>{const b=e.target.closest('[data-del]');if(!b)return;readMenu();menu.splice(+b.dataset.del,1);renderMenu()};
 try{tg?.ready();tg?.expand()}catch{};bootstrap().catch(e=>{$('#gateText').textContent=e.message});
})();