(() => {
 const {api,esc}=SHAURMEG,tg=SHAURMEG.telegram,$=s=>document.querySelector(s);
 let session=sessionStorage.getItem('shaurmeg_admin_session')||'',token=sessionStorage.getItem('shaurmeg_owner_token')||'',map,points=[],markers=new Map(),pressTimer=null,superMenu=[];
 const authHeaders=()=>session?{Authorization:'Bearer '+session}:{'X-Owner-Token':token};
 function toast(v){$('#toast').textContent=v;$('#toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('#toast').classList.remove('show'),1600)}
 async function apiCall(path,opt={}){opt.headers={...(opt.headers||{}),...authHeaders()};if(opt.body){opt.headers['Content-Type']='application/json';if(typeof opt.body!=='string')opt.body=JSON.stringify(opt.body)}const r=await fetch(api+path,opt);if(!r.ok){const j=await r.json().catch(()=>({}));throw new Error(j.error||'HTTP '+r.status)}return r.json()}
 async function authTelegram(){
   if(!tg?.initData)return false;try{const r=await fetch(api+'/admin/auth/telegram',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({initData:tg.initData})});if(!r.ok)return false;const j=await r.json();session=j.session;sessionStorage.setItem('shaurmeg_admin_session',session);return true}catch{return false}
 }
 async function login(){try{const r=await fetch(api+'/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('#password').value})});if(!r.ok)throw 0;const j=await r.json();token=j.token;sessionStorage.setItem('shaurmeg_owner_token',token);await start()}catch{$('#loginError').textContent='Не удалось войти'}}
 function markerNode(p){const el=document.createElement('button');el.className='mapMarker';el.textContent=p.marker_style?.icon||'🥙';el.style.background=p.marker_style?.background||'#10221b';el.onclick=e=>{e.stopPropagation();edit(p)};return el}
 async function initMap(){map=new maplibregl.Map({container:'map',style:'https://tiles.openfreemap.org/styles/liberty',center:[37.6176,55.7558],zoom:10.5,pitch:38,bearing:-10});map.addControl(new maplibregl.NavigationControl(),'bottom-right');
   map.on('mousedown',e=>{pressTimer=setTimeout(()=>newAt(e.lngLat),700)});map.on('mouseup',()=>clearTimeout(pressTimer));map.on('mousemove',()=>clearTimeout(pressTimer));map.on('touchstart',e=>{const ll=e.lngLat;pressTimer=setTimeout(()=>newAt(ll),750)});map.on('touchend',()=>clearTimeout(pressTimer));
 }
 async function load(){points=await apiCall('/admin/markers');markers.forEach(m=>m.remove());markers.clear();points.forEach(p=>markers.set(String(p.id),new maplibregl.Marker({element:markerNode(p)}).setLngLat([+p.lon,+p.lat]).addTo(map)));renderList()}
 function renderList(){$('#pointList').innerHTML=points.length?points.map(p=>'<button class="listRow" data-id="'+p.id+'"><div class="grow"><b>'+esc(p.name)+'</b><small>'+esc(p.address||'')+' · '+esc(p.establishment_id||'')+'</small></div><span>›</span></button>').join(''):'<div class="empty">Точек пока нет</div>'}
 function fill(p={}){$('#editor').dataset.establishment=p.establishment_id||'';$('#id').value=p.id||'';$('#name').value=p.name||'';$('#address').value=p.address||'';$('#description').value=p.description||'';$('#lat').value=p.lat??'';$('#lon').value=p.lon??'';$('#icon').value=p.marker_style?.icon||'🥙';$('#background').value=p.marker_style?.background||'#10221b';$('#hours').value=p.hours||'';$('#price').value=p.price_label||'';$('#editTitle').textContent=p.id?'Редактировать точку':'Новая точка';$('#deletePoint').classList.toggle('hidden',!p.id);$('#ownerTools').classList.toggle('hidden',!p.establishment_id);$('#realcityTools').classList.toggle('hidden',!p.id);$('#realcityStatus').textContent=p.id?'Статус: '+(p.realcity_status||'pending')+(p.realcity_quality?' · '+p.realcity_quality:''):'';$('#establishmentLabel').textContent=p.establishment_id||'';$('#inviteOutput').classList.add('hidden');$('#editor').classList.remove('hidden')}
 function edit(p){fill(p);map.easeTo({center:[+p.lon,+p.lat],zoom:16.8,pitch:52,duration:650});loadSuperMenu(p)}
 async function loadSuperMenu(p){if(!p?.id||!p.establishment_id){$('#superMenuPanel').classList.add('hidden');return}try{const r=await fetch(api+'/menu-context?marker_id='+encodeURIComponent(p.id)+'&establishment_id='+encodeURIComponent(p.establishment_id),{cache:'no-store'});if(!r.ok)throw 0;const x=await r.json();superMenu=(x.venue.menu||[]).map(v=>({...v}));renderSuperMenu();$('#superMenuPanel').classList.remove('hidden')}catch{$('#superMenuPanel').classList.add('hidden')}}
 function renderSuperMenu(){$('#superMenuEditor').innerHTML=superMenu.length?superMenu.map((x,i)=>'<div class="menuEditRow" data-sm="'+i+'"><input data-k="n" value="'+esc(x.n||x.name||'')+'" placeholder="Название"><input class="desc" data-k="d" value="'+esc(x.d||x.description||'')+'" placeholder="Описание"><input data-k="p" value="'+esc(x.p??x.price??0)+'" inputmode="decimal"><button class="dangerBtn" type="button" data-sdel="'+i+'">×</button></div>').join(''):'<div class="empty">Меню пустое</div>'}
 function readSuperMenu(){document.querySelectorAll('[data-sm]').forEach(row=>{const x=superMenu[+row.dataset.sm];row.querySelectorAll('[data-k]').forEach(inp=>x[inp.dataset.k]=inp.dataset.k==='p'?+inp.value:inp.value);x.id=x.id||'item_'+Date.now()+'_'+row.dataset.sm;x.c=x.c||'shawarma';x.active=true})}
 async function saveSuperMenu(){const est=$('#editor').dataset.establishment;if(!est)return;readSuperMenu();try{await apiCall('/admin/venues/'+encodeURIComponent(est)+'/menu',{method:'PUT',body:{menu:superMenu}});toast('Меню точки сохранено ✓')}catch(e){toast(e.message)}}
 function newAt(ll){fill({lat:+ll.lat.toFixed(6),lon:+ll.lng.toFixed(6)});toast('Координаты выбраны')}
 async function save(e){e.preventDefault();const id=$('#id').value,b={name:$('#name').value,address:$('#address').value,description:$('#description').value,lat:+$('#lat').value,lon:+$('#lon').value,hours:$('#hours').value,price_label:$('#price').value,category:'shawarma',marker_style:{icon:$('#icon').value,background:$('#background').value,border:'#f6f3e9',text:'#ffffff',glow:'#8fe0a9',shape:'rounded',size:44,scale:1,opacity:1,pulse:true,label_visible:false},is_active:true};try{const saved=await apiCall(id?'/admin/markers/'+id:'/admin/markers',{method:id?'PUT':'POST',body:b});toast('Сохранено ✓');await load();const fresh=points.find(x=>String(x.id)===String(saved.id));if(fresh)edit(fresh)}catch(e){toast(e.message)}}
 function dataUrl(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||''));r.onerror=reject;r.readAsDataURL(file)})}
 async function waitRealCity(id){for(let i=0;i<18;i++){await new Promise(r=>setTimeout(r,1200));const s=await apiCall('/admin/markers/'+id+'/realcity');$('#realcityStatus').textContent='Статус: '+s.realcity_status+(s.realcity_quality?' · '+s.realcity_quality:'');if(s.realcity_status==='ready'||s.realcity_status==='failed')return s}return null}
 async function analyzeFacade(){const id=$('#id').value,files=[...$('#facadeFiles').files].slice(0,8);if(!id)return toast('Сначала сохраните точку');if(!files.length)return toast('Выберите фото фасада');try{const refs=[];for(let i=0;i<files.length;i++){if(files[i].size>2500000)throw new Error('Фото '+(i+1)+' слишком большое');refs.push({src:await dataUrl(files[i]),role:i===0?'hero_facade':'environment'})}$('#realcityStatus').textContent='Загрузка и анализ…';await apiCall('/admin/markers/'+id+'/realcity',{method:'PUT',body:{reference_images:refs}});const s=await waitRealCity(id);if(s?.realcity_status==='ready'){toast('Фасад проанализирован ✓');await load();const fresh=points.find(x=>String(x.id)===String(id));if(fresh)edit(fresh)}else toast('Анализ ещё выполняется')}catch(e){toast(e.message)}}
 async function rebuildRealcity(){const id=$('#id').value;if(!id)return;try{$('#realcityStatus').textContent='Пересборка…';await apiCall('/admin/markers/'+id+'/realcity/rebuild',{method:'POST'});const s=await waitRealCity(id);toast(s?.realcity_status==='ready'?'RealCity обновлён ✓':'Пересборка запущена')}catch(e){toast(e.message)}}
 async function grantOwner(){const est=$('#editor').dataset.establishment,uid=$('#ownerTgId').value.trim();if(!est)return toast('Сначала сохраните точку');if(!uid)return toast('Введите Telegram ID');try{await apiCall('/admin/venues/'+encodeURIComponent(est)+'/admins',{method:'POST',body:{telegram_user_id:uid,role:'owner'}});toast('Доступ владельцу выдан ✓')}catch(e){toast(e.message)}}
 async function inviteOwner(){const est=$('#editor').dataset.establishment;if(!est)return toast('Сначала сохраните точку');try{const x=await apiCall('/admin/venues/'+encodeURIComponent(est)+'/invites',{method:'POST',body:{hours:72,role:'owner'}});$('#inviteOutput').textContent='Код: '+x.code+' · действует до '+new Date(x.expires_at).toLocaleString('ru-RU');$('#inviteOutput').classList.remove('hidden');try{await navigator.clipboard.writeText(x.code)}catch{}toast('Код владельца создан и скопирован')}catch(e){toast(e.message)}}
 async function del(){const id=$('#id').value;if(!id||!confirm('Скрыть эту точку с карты?'))return;try{await apiCall('/admin/markers/'+id,{method:'DELETE'});$('#editor').classList.add('hidden');toast('Точка удалена');await load()}catch(e){toast(e.message)}}
 async function start(){$('#gate').classList.add('hidden');if(!map)await initMap();await new Promise(r=>map.loaded()?r():map.once('load',r));await load()}
 $('#superAddItem').onclick=()=>{readSuperMenu();superMenu.push({id:'item_'+Date.now(),n:'Новая позиция',d:'',p:0,c:'shawarma',active:true});renderSuperMenu()};$('#superSaveMenu').onclick=saveSuperMenu;$('#superMenuEditor').onclick=e=>{const b=e.target.closest('[data-sdel]');if(!b)return;readSuperMenu();superMenu.splice(+b.dataset.sdel,1);renderSuperMenu()};$('#newPoint').onclick=()=>{fill({});$('#superMenuPanel').classList.add('hidden')};$('#editor').onsubmit=save;$('#deletePoint').onclick=del;$('#grantOwner').onclick=grantOwner;$('#inviteOwner').onclick=inviteOwner;$('#analyzeFacade').onclick=analyzeFacade;$('#rebuildRealcity').onclick=rebuildRealcity;$('#pointList').onclick=e=>{const b=e.target.closest('[data-id]'),p=b&&points.find(x=>String(x.id)===b.dataset.id);if(p)edit(p)};$('#login').onclick=login;
 (async()=>{try{tg?.ready();tg?.expand()}catch{};if(session||token)return start();if(await authTelegram())return start();$('#gate').classList.remove('hidden')})().catch(e=>toast(e.message));
})();