(() => {
 const {api,esc}=SHAURMEG,tg=SHAURMEG.telegram,$=s=>document.querySelector(s);
 let session=sessionStorage.getItem('shaurmeg_admin_session')||'',token=sessionStorage.getItem('shaurmeg_owner_token')||'',map,points=[],markers=new Map(),pressTimer=null;
 const authHeaders=()=>session?{Authorization:'Bearer '+session}:{'X-Owner-Token':token};
 function toast(v){$('#toast').textContent=v;$('#toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('#toast').classList.remove('show'),1600)}
 async function apiCall(path,opt={}){opt.headers={...(opt.headers||{}),...authHeaders()};if(opt.body){opt.headers['Content-Type']='application/json';if(typeof opt.body!=='string')opt.body=JSON.stringify(opt.body)}const r=await fetch(api+path,opt);if(!r.ok){const j=await r.json().catch(()=>({}));throw new Error(j.error||'HTTP '+r.status)}return r.json()}
 async function authTelegram(){
   if(!tg?.initData)return false;try{const r=await fetch(api+'/admin/auth/telegram',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({initData:tg.initData})});if(!r.ok)return false;const j=await r.json();session=j.session;sessionStorage.setItem('shaurmeg_admin_session',session);return true}catch{return false}
 }
 async function login(){try{const r=await fetch(api+'/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('#password').value})});if(!r.ok)throw 0;const j=await r.json();token=j.token;sessionStorage.setItem('shaurmeg_owner_token',token);await start()}catch{$('#loginError').textContent='Не удалось войти'}}
 function markerNode(p){const el=document.createElement('button');el.className='mapMarker';el.textContent=p.marker_style?.icon||'🥙';el.style.background=p.marker_style?.background||'#10221b';el.onclick=e=>{e.stopPropagation();edit(p)};return el}
 async function initMap(){map=new maplibregl.Map({container:'map',style:'https://tiles.openfreemap.org/styles/liberty',center:[37.6176,55.7558],zoom:10.5,pitch:38,bearing:-10});map.addControl(new maplibregl.NavigationControl(),'bottom-right');
   map.on('mousedown',e=>{pressTimer=setTimeout(()=>newAt(e.lngLat),700)});map.on('mouseup',()=>clearTimeout(pressTimer));map.on('mousemove',()=>clearTimeout(pressTimer));map.on('touchstart',e=>{const ll=e.lngLat;pressTimer=setTimeout(()=>newAt(ll),750)});map.on('touchend',()=>clearTimeout(pressTimer));
 }
 async function load(){points=await apiCall('/admin/markers');markers.forEach(m=>m.remove());markers.clear();points.forEach(p=>markers.set(String(p.id),new maplibregl.Marker({element:markerNode(p)}).setLngLat([+p.lon,+p.lat]).addTo(map)));renderList()}
 function renderList(){$('#pointList').innerHTML=points.length?points.map(p=>'<button class="listRow" data-id="'+p.id+'"><div class="grow"><b>'+esc(p.name)+'</b><small>'+esc(p.address||'')+' · '+esc(p.establishment_id||'')+'</small></div><span>›</span></button>').join(''):'<div class="empty">Точек пока нет</div>'}
 function fill(p={}){$('#editor').dataset.establishment=p.establishment_id||'';$('#id').value=p.id||'';$('#name').value=p.name||'';$('#address').value=p.address||'';$('#description').value=p.description||'';$('#lat').value=p.lat??'';$('#lon').value=p.lon??'';$('#icon').value=p.marker_style?.icon||'🥙';$('#background').value=p.marker_style?.background||'#10221b';$('#hours').value=p.hours||'';$('#price').value=p.price_label||'';$('#editTitle').textContent=p.id?'Редактировать точку':'Новая точка';$('#deletePoint').classList.toggle('hidden',!p.id);$('#ownerTools').classList.toggle('hidden',!p.establishment_id);$('#establishmentLabel').textContent=p.establishment_id||'';$('#inviteOutput').classList.add('hidden');$('#editor').classList.remove('hidden')}
 function edit(p){fill(p);map.easeTo({center:[+p.lon,+p.lat],zoom:16.8,pitch:52,duration:650})}
 function newAt(ll){fill({lat:+ll.lat.toFixed(6),lon:+ll.lng.toFixed(6)});toast('Координаты выбраны')}
 async function save(e){e.preventDefault();const id=$('#id').value,b={name:$('#name').value,address:$('#address').value,description:$('#description').value,lat:+$('#lat').value,lon:+$('#lon').value,hours:$('#hours').value,price_label:$('#price').value,category:'shawarma',marker_style:{icon:$('#icon').value,background:$('#background').value,border:'#f6f3e9',text:'#ffffff',glow:'#8fe0a9',shape:'rounded',size:44,scale:1,opacity:1,pulse:true,label_visible:false},is_active:true};try{const saved=await apiCall(id?'/admin/markers/'+id:'/admin/markers',{method:id?'PUT':'POST',body:b});toast('Сохранено ✓');await load();const fresh=points.find(x=>String(x.id)===String(saved.id));if(fresh)edit(fresh)}catch(e){toast(e.message)}}
 async function grantOwner(){const est=$('#editor').dataset.establishment,uid=$('#ownerTgId').value.trim();if(!est)return toast('Сначала сохраните точку');if(!uid)return toast('Введите Telegram ID');try{await apiCall('/admin/venues/'+encodeURIComponent(est)+'/admins',{method:'POST',body:{telegram_user_id:uid,role:'owner'}});toast('Доступ владельцу выдан ✓')}catch(e){toast(e.message)}}
 async function inviteOwner(){const est=$('#editor').dataset.establishment;if(!est)return toast('Сначала сохраните точку');try{const x=await apiCall('/admin/venues/'+encodeURIComponent(est)+'/invites',{method:'POST',body:{hours:72,role:'owner'}});$('#inviteOutput').textContent='Код: '+x.code+' · действует до '+new Date(x.expires_at).toLocaleString('ru-RU');$('#inviteOutput').classList.remove('hidden');try{await navigator.clipboard.writeText(x.code)}catch{}toast('Код владельца создан и скопирован')}catch(e){toast(e.message)}}
 async function del(){const id=$('#id').value;if(!id||!confirm('Скрыть эту точку с карты?'))return;try{await apiCall('/admin/markers/'+id,{method:'DELETE'});$('#editor').classList.add('hidden');toast('Точка удалена');await load()}catch(e){toast(e.message)}}
 async function start(){$('#gate').classList.add('hidden');if(!map)await initMap();await new Promise(r=>map.loaded()?r():map.once('load',r));await load()}
 $('#newPoint').onclick=()=>fill({});$('#editor').onsubmit=save;$('#deletePoint').onclick=del;$('#grantOwner').onclick=grantOwner;$('#inviteOwner').onclick=inviteOwner;$('#pointList').onclick=e=>{const b=e.target.closest('[data-id]'),p=b&&points.find(x=>String(x.id)===b.dataset.id);if(p)edit(p)};$('#login').onclick=login;
 (async()=>{try{tg?.ready();tg?.expand()}catch{};if(session||token)return start();if(await authTelegram())return start();$('#gate').classList.remove('hidden')})().catch(e=>toast(e.message));
})();