#!/usr/bin/env bash
set -euo pipefail

export REALCITY_LIGHTWEIGHT_CPU=false
export REALCITY_HIGH_MEMORY_CPU=true
export REALCITY_ALLOW_CPU_MAPANYTHING=true
export REALCITY_MAX_BACKEND=mapanything
export REALCITY_USE_BA=${REALCITY_USE_BA:-true}
export REALCITY_USE_GSPLAT=false
export REALCITY_ALLOW_DEPTH_FALLBACK=${REALCITY_ALLOW_DEPTH_FALLBACK:-true}
export REALCITY_GPU_CONCURRENCY=1
export REALCITY_CPU_MAX_FRAMES=${REALCITY_CPU_MAX_FRAMES:-32}
export OMP_NUM_THREADS=${OMP_NUM_THREADS:-12}
export MKL_NUM_THREADS=${MKL_NUM_THREADS:-12}
export TOKENIZERS_PARALLELISM=false
export PYTORCH_ENABLE_MPS_FALLBACK=1

exec uvicorn app:app --host 0.0.0.0 --port "${PORT:-8000}" --workers 1
