'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const express=require('express');
const config=require('../src/config'),auth=require('../src/auth'),db=require('../src/db');
const {router}=require('../src/routes');
test('authenticated design updates patch only their own JSON field and retain venue permissions',async()=>{
 const savedKey=config.VENUE_OWNER_BOT_TOKEN,savedQuery=db.query;config.VENUE_OWNER_BOT_TOKEN='isolated-test-key';
 const est='SC-MSK-9342972B1F',state={config:{builder_enabled:true,menu_sections:[{id:'wrap'}],theme:{primary:'#123456'},site_customization:{design:{radius:22}}}},queries=[];
 db.query=async(sql,p=[])=>{queries.push({sql,p});if(sql.startsWith('SELECT * FROM shaurma_venue_admins'))return {rows:p[0]===est&&p[1]==='42'?[{role:'owner',permissions:['profile']}]:[]};if(sql.startsWith('SELECT config'))return {rows:[{config:structuredClone(state.config)}]};if(sql.startsWith('UPDATE shaurma_venues')){const field=sql.includes("jsonb_build_object('theme'")?'theme':sql.includes("jsonb_build_object('site_customization'")?'site_customization':null;assert.ok(field,'must use a field-scoped atomic update');assert.equal(p[0],est);state.config[field]=JSON.parse(p[1]);if(p.length===3){assert.ok(sql.includes("'site_customization',$3::jsonb"));state.config.site_customization=JSON.parse(p[2])}return {rows:[{establishment_id:est,config:structuredClone(state.config)}]}}if(sql.startsWith('INSERT INTO shaurma_venue_audit'))return {rows:[]};throw Error('Unexpected query '+sql)};
 const app=express();app.use(express.json());app.use('/api/v2',router);const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port+'/api/v2/venue-owner/establishments/',headers={'Content-Type':'application/json',Authorization:'Bearer '+auth.sign({id:42},'venue')};
 try{const [a,b]=await Promise.all([fetch(base+est+'/theme',{method:'PUT',headers,body:JSON.stringify({theme:{primary:'#AA3344',secondary:'#102030',tone:'dark'}})}),fetch(base+est+'/site',{method:'PUT',headers,body:JSON.stringify({site_customization:{design:{mode:'glass',radius:28},builder_result:{title:'Авторская сборка'},features:{favorites:false}}})})]);assert.equal(a.status,200);assert.equal(b.status,200);assert.equal(state.config.theme.primary,'#AA3344');assert.equal(state.config.site_customization.design.radius,28);assert.equal(state.config.site_customization.builder_result.title,'Авторская сборка');const combined=await fetch(base+est+'/design',{method:'PUT',headers,body:JSON.stringify({theme:{primary:'#3355AA'},site_customization:{menu:{layout:'uniform-3'},builder_result:{title:'Финальная сборка'}}})});assert.equal(combined.status,200);assert.equal(state.config.theme.primary,'#3355AA');assert.equal(state.config.site_customization.menu.layout,'uniform-3');assert.equal(state.config.site_customization.builder_result.title,'Финальная сборка');assert.equal(state.config.builder_enabled,true);assert.deepEqual(state.config.menu_sections,[{id:'wrap'}]);const denied=await fetch(base+'SC-MSK-ABCDEF1234'+'/design',{method:'PUT',headers,body:'{}'});assert.equal(denied.status,403);const anonymous=await fetch(base+est+'/design',{method:'PUT',headers:{'Content-Type':'application/json'},body:'{}'});assert.equal(anonymous.status,401);assert.equal(queries.filter(x=>x.sql.startsWith('UPDATE')).length,3)}
 finally{server.closeAllConnections();await new Promise(r=>server.close(r));db.query=savedQuery;config.VENUE_OWNER_BOT_TOKEN=savedKey}
});
